#!/bin/bash

#ubuntu ROS2 installation

#setup locale to en_US
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8

#Ensure that the ubuntu universe repo is enabled
sudo apt install software-properties-common -y
sudo add-apt-repository universe

#add ros 2 gpg key to download
sudo apt update && sudo apt install curl -y
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

#add repo to source list and download
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
sudo apt update
sudo apt upgrade -y

#Desktop installation of humble
sudo apt install ros-humble-desktop -y
sudo apt install ros-dev-tools -y
sudo apt install libudev-dev

#Install colcon to build package
sudo apt install python3-colcon-common-extensions

#Install pip and set good version of setuptools
sudo apt-get -y install python3-pip
pip install setuptools==58.2.0

#Setup sources
echo "source /opt/ros/humble/setup.bash" >> .bashrc


